### ISSUE TITLE
Lipschitz constant in multidimentional DIRECT method

### ISSUE THREAD

**Issue by mykelk** [sisl/algforopt-errata#18]
The second to last sentence of Sec. 7.6.2 says: "The lower bound for each hyper-rectangle can be computed based on the longest side length and center value." However, I think it should be the distance to the vertex (the diagonal distance). See Def. 4.1 in the original 1993 paper, which says "let d_i denote the distance from the center point to the vertices". Interestingly, fig. 7.12 in the book correctly shows the lower bound decaying as it approaches the vertices.

**Comment by tawheeler** [comment]
I see what you are saying. 

Actually, we are talking about the set of potentially optimal intervals. The "lower bound" here refers to the blue piecewise boundary line in Figure 7.17. 

In the multivariate case direct still uses the longest side length to construct the equivalent data structure for figure 7.17:
```
d = min_depth(interval)
if !haskey(intervals, d)
    intervals[d] = PriorityQueue{Interval, Float64}()
end
```
The list of priority queues are indexed by minimum depth, which is the same as maximum side length.

**Comment by mykelk** [comment]
@rbalexan if you have a proposed fix to the Julia code, we can try it out and work it in to the next printing!

**Comment by rbalexan** [comment]
I think all that's needed is to compute the interval's diagonal half-length instead of the largest side's half-length. This amounts to changing: 

`x, y = 0.5*3.0^(-min_depth(I)), I.y` to 
`x, y = norm(0.5*3.0.^(-I.depths)), I.y`
 
in each instance of this computation (looks like there are three in the function). This way, the Lipschitz constant calculations that occur later are computed on the diagonal half-length, which matches the definition of the multi-dimensional Lipschitz lower bound. 

I think this is all that's required. When I make these modifications on the existing code, it runs and converges similarly, which is a good sign.

Might also be good to look into an alternate name for `x` (maybe `d` or `hd` for (half)-diagonal...??).

**Comment by tawheeler** [comment]
the problem is that we are currently using the maximum depth to index into the list of priority queues. We'll have to order by this floating-point maximum length instead. There is a chance this will change pagination, which we're not allowed to do between minor releases.
This is definitely an issue.

**Comment by tawheeler** [comment]
I can probably use a SortedDict from DataStructures.jl

**Comment by tawheeler** [comment]
That worked

```julia
min_depth(interval) = minimum(interval.depths)
vertex_dist(I) = norm(0.5*3.0.^(-I.depths), 2)
const Intervals =
		OrderedDict{Float64,PriorityQueue{Interval, Float64}}
function add_interval!(intervals, interval)
	d = vertex_dist(interval)
    if !haskey(intervals, d)
        intervals[d] = PriorityQueue{Interval, Float64}()
    end
    return enqueue!(intervals[d], interval, interval.y)
end

function get_opt_intervals(intervals, ϵ, y_best)
    stack = Interval[]
    for (d, pq) in intervals
    	if !isempty(pq)
            interval = DataStructures.peek(pq)[1]
            x, y = d, interval.y
            while !isempty(stack)
            	interval1 = stack[end]
            	x1, y1 = vertex_dist(interval1), interval1.y
            	L1 = (y - y1)/(x - x1)
            	if y1 - L1*x1 > f_best - ϵ || y < y1
            		pop!(stack)
            	elseif length(stack) > 1
            		interval2 = stack[end-1]
            		x2, y2 = vertex_dist(interval2), interval2.y
            		L2 = (y1 - y2)/(x1 - x2)
            		if L2 > L1
            			pop!(stack)
                    else
                        break
            		end
                else
                    break
            	end
           	end
            push!(stack, interval) # add new interval
        end
    end
```

For what its worth, we use x and y because they correspond to the x and y axes in the interval plots. It may not be the best, but I certainly don't want to change it between normal reprints.

**Comment by rbalexan** [comment]
Glad that worked - I was worried about duplicate keys due to multiple hyperrectangles having the same diagonal lengths and thus the same key in the OrderedDict, but that may be handled by the type. Makes sense not to change `x, y` between the minor reprints. 

Only suggestion would be to update the function argument for `vertex_dist` to match the function arguments above. I grabbed the code from the online notebooks, which used `I.depths` instead of `interval.depths`, but the book uses `interval.depths` throughout.

```julia
min_depth(interval)   = minimum(interval.depths)
vertex_dist(I)        = norm(0.5*3.0.^(-I.depths), 2)
```

to 

```julia
min_depth(interval)   = minimum(interval.depths)
vertex_dist(interval) = norm(0.5*3.0.^(-interval.depths), 2)
```

**Comment by tawheeler** [comment]
Multiple cells can absolutely have the same key. They all end up in the same priority queue. That way we can easily access the best one.

Good call - I went ahead and updated that as well, and updated the figure-generating code to be consistent.
